{{- range .Values.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-service
spec:
  type: {{ .serviceType }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
  selector:
    app: {{ .name }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}-deployment
  labels:
    app: {{ .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .name }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .strategy.name }}
      maxUnavailable: {{ .strategy.maxUnavailable }}
    type: {{ .strategy.type }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}-image
          image: {{ .image }}
          imagePullPolicy: {{ .imagePullPolicy }}
          {{- if .env }}
          env:
            {{- range .env }}
            - name: {{ .name | quote}}
              value: {{ .value | quote}}
            {{- end }}
          {{- end }}
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
            requests:
              memory: "128Mi"
              cpu: "50m"

---
{{- end }}