apiVersion: v1  
kind: LimitRange  
metadata:  
  name: {{ .Release.Name}}-default-resources  
{{- with .Values.resources}}
spec:  
  limits: 
    - default:
        memory: {{ .memory | quote }}  
        cpu: {{ .cpu | quote }}   
      defaultRequest:  
        memory: {{ .request.memory | quote }}  
        cpu: {{ .request.cpu | quote }}  
      type: Container
  
{{- if .quota }}
---

apiVersion: v1  
kind: ResourceQuota  
metadata:  
  name: {{ $.Release.Name}}-quota  
spec:  
  hard:
    limits.cpu: {{ .limits.cpu | quote }}    
    limits.memory: {{ .limits.memory | quote }} 

{{- end }}
{{- end }}